### ISSUE TITLE
GPU Miner ProgPow Epoch

### ISSUE THREAD

**Issue by Djadih** [dominant-strategies/quai-gpu-miner-archive#20]
Coordinate epoch transition across shards for progpow.

**Comment by Djadih** [comment]
3 caches
1. For current progpow epoch work
2. Previous epoch work
3. Future epoch work (as it is generated)

Have a FIFO queue where we try to verify work against the first 2 caches starting by current then previous

**Comment by mibuono** [comment]
We need to understand why the cache can't update fast enough.  Please provide more details here in the ticket @Djadih

**Comment by mibuono** [comment]
The real epoch we have to set is 2 months for mainnet.  For testnet we need to set the Epoch to a week.

Do we want to modify the rate of increase?
The rate per year should be on the order of 30% per year.

Zone number is baked into the seal hash- and use the prime number everywhere.

**Comment by Djadih** [comment]
ProgPow:

PROGPOW_PERIOD: Number of blocks before changing the random program - keep what it was.
PROGPOW_LANES: The number of parallel lanes that coordinate to calculate a single hash instance
PROGPOW_REGS: The register file usage size
PROGPOW_DAG_LOADS: Number of uint32 loads from the DAG per lane
PROGPOW_CACHE_BYTES: The size of the cache
PROGPOW_CNT_DAG: The number of DAG accesses, defined as the outer loop of the algorithm (64 is the same as Ethash)
PROGPOW_CNT_CACHE: The number of cache accesses per loop
PROGPOW_CNT_MATH: The number of math operations per loop
ETHASH_DATASET_PARENTS
EPOCH - Set to 1 week in prime block numbers (144x7)

**Comment by Djadih** [comment]
- Epoch will be approximately 1 month:
  - To avoid ASICs from being pre-developed and ROI within that period
- Period can stay 10 blocks
- Epoch and period calculations need to reference Prime (*Done*)

**Comment by Djadih** [comment]
Prime blocks are approximately 10 minutes apart. Therefore they have approximately 50 zone blocks produced in each zone.

There are approximately 216000 zone blocks in a month, therefore about 4320 prime blocks should be the epoch length.

**Comment by mibuono** [comment]
Potential issue for next sprint
